driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
    run_list:
    - recipe[yum-epel]
  - name: centos-6.7
    run_list:
    - recipe[yum-epel]
  - name: centos-7.1
    run_list:
    - recipe[yum-epel]
  - name: debian-7.8
    run_list:
    - recipe[apt]
  - name: debian-8.1
    run_list:
    - recipe[apt]
  - name: freebsd-10.2
  - name: fedora-21
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[zsh]
